### ISSUE TITLE
@cached_property not identifies as a a property in docstrings

### ISSUE THREAD

**Issue by arturo-seijas** [jdkandersson/flake8-docstrings-complete#11]
The decorator @cached_property is not identified as a property, causing DCO064 to be raised:
`DCO064 "certificates" attribute should not be described in the docstring, more information: https://github.com/jdkandersson/flake8-docstrings-complete#fix-dco064`

It is my understanding that properties annotated with this decorator should also be present as attributes in the docstring

**Comment by jdkandersson** [comment]
Should be fixed in release v1.2.0
